# Generated by Django 2.1 on 2018-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('coins_id', models.CharField(blank=True, default='', max_length=28, null=True)),
                ('coins_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('coins_symbol', models.CharField(blank=True, default='', max_length=28, null=True)),
                ('event_description', models.TextField(blank=True, default='', null=True)),
                ('event_proof', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('event_source', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_created_date', models.DateTimeField(blank=True, null=True)),
                ('event_feed_source', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('event_is_hot', models.BooleanField(default='False')),
                ('event_vote_count', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('event_positive_vote_count', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('event_percentage', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('event_event_cat_id', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('event_event_cat_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('event_tip_symbol', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('event_tip_adress', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('event_twitter_account', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GetEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=128)),
            ],
        ),
    ]
