# Generated by Django 2.0.5 on 2018-08-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coinmarketcap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_coin_id', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_symbol', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_rank', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_price_usd', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_price_btc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_price_pln', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_capitalization', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_volume_usd_24h', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_capitalization_pln', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_market_cap_usd', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_available_supply', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_total_supply', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_max_supply', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('cmc_percent_change_1h', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('cmc_percent_change_24h', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('cmc_percent_change_7d', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('cmc_last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
