# Generated by Django 2.1 on 2018-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketcap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditCoinmarketcap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=128)),
            ],
        ),
    ]
