# Generated by Django 2.1 on 2018-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_feed_title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('rss_feed_description', models.TextField(blank=True, default='', null=True)),
                ('rss_feed_img', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('rss_feed_link', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('rss_feed_published', models.DateTimeField(blank=True, null=True)),
                ('rss_feed_source', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GetFeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=128)),
            ],
        ),
    ]
