# Generated by Django 2.1 on 2018-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.IntegerField(default=0)),
                ('rodzaj', models.IntegerField(choices=[(2, 'Komedia'), (4, 'Drama'), (0, 'Nieznany'), (3, 'Sci-Fi'), (1, 'Horror')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GetMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('icci_cat', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('icci_sub_cat', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('title', models.CharField(default='', max_length=128)),
                ('videoID', models.CharField(default='', max_length=128)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('channelId', models.CharField(default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('categoryId', models.CharField(default='', max_length=128)),
                ('liveBroadcastContent', models.CharField(default='', max_length=128)),
                ('defaultLanguage', models.CharField(default='', max_length=128)),
                ('duration', models.CharField(default='', max_length=20)),
                ('dimension', models.CharField(default='', max_length=20)),
                ('definition', models.CharField(default='', max_length=10)),
                ('caption', models.CharField(default='', max_length=10)),
                ('licensedContent', models.BooleanField(default='False')),
                ('projection', models.CharField(default='', max_length=20)),
                ('viewCount', models.CharField(default='', max_length=20)),
                ('likeCount', models.CharField(default='', max_length=20)),
                ('dislikeCount', models.CharField(default='', max_length=20)),
                ('favoriteCount', models.CharField(default='', max_length=20)),
                ('commentCount', models.CharField(default='', max_length=20)),
                ('thumbnails_default', models.CharField(default='', max_length=80)),
                ('thumbnails_medium', models.CharField(default='', max_length=80)),
                ('thumbnails_high', models.CharField(default='', max_length=80)),
                ('thumbnails_standard', models.CharField(default='', max_length=80)),
                ('thumbnails_maxres', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
