# Generated by Django 2.1 on 2018-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(3, 'Sci-Fi'), (2, 'Komedia'), (4, 'Drama'), (1, 'Horror'), (0, 'Nieznany')], default=0),
        ),
    ]
